/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FreelancerRouteImport } from './routes/freelancer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as FreelancerIndexRouteImport } from './routes/freelancer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as PortalContractsRouteImport } from './routes/portal.contracts'
import { Route as FreelancerRequestsRouteImport } from './routes/freelancer.requests'
import { Route as FreelancerOpenRouteImport } from './routes/freelancer.open'
import { Route as FreelancerFinanceRouteImport } from './routes/freelancer.finance'
import { Route as AdminWebdesignRouteImport } from './routes/admin.webdesign'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminPartnerRequestsRouteImport } from './routes/admin.partner-requests'
import { Route as AdminFreelancersRouteImport } from './routes/admin.freelancers'
import { Route as AdminContractsRouteImport } from './routes/admin.contracts'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminAssignmentsRouteImport } from './routes/admin.assignments'
import { Route as AdminFreelancersIndexRouteImport } from './routes/admin.freelancers.index'
import { Route as AdminContractsIndexRouteImport } from './routes/admin.contracts.index'
import { Route as AdminClientsIndexRouteImport } from './routes/admin.clients.index'
import { Route as AdminAssignmentsIndexRouteImport } from './routes/admin.assignments.index'
import { Route as PortalServicesSlugRouteImport } from './routes/portal.services.$slug'
import { Route as AdminServicesSlugRouteImport } from './routes/admin.services.$slug'
import { Route as AdminFreelancersSettlementsRouteImport } from './routes/admin.freelancers.settlements'
import { Route as AdminFreelancersIdRouteImport } from './routes/admin.freelancers.$id'
import { Route as AdminContractsNewRouteImport } from './routes/admin.contracts.new'
import { Route as AdminContractsIdRouteImport } from './routes/admin.contracts.$id'
import { Route as AdminClientsNewRouteImport } from './routes/admin.clients.new'
import { Route as AdminClientsInviteRouteImport } from './routes/admin.clients.invite'
import { Route as AdminClientsClientIdRouteImport } from './routes/admin.clients.$clientId'
import { Route as PortalServicesWebdesignMaintenanceRouteImport } from './routes/portal.services.webdesign.maintenance'
import { Route as PortalServicesSocialMediaScriptsRouteImport } from './routes/portal.services.social-media.scripts'
import { Route as PortalServicesSocialMediaCalendarRouteImport } from './routes/portal.services.social-media.calendar'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerRoute = FreelancerRouteImport.update({
  id: '/freelancer',
  path: '/freelancer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const FreelancerIndexRoute = FreelancerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FreelancerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalContractsRoute = PortalContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => PortalRoute,
} as any)
const FreelancerRequestsRoute = FreelancerRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => FreelancerRoute,
} as any)
const FreelancerOpenRoute = FreelancerOpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => FreelancerRoute,
} as any)
const FreelancerFinanceRoute = FreelancerFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => FreelancerRoute,
} as any)
const AdminWebdesignRoute = AdminWebdesignRouteImport.update({
  id: '/webdesign',
  path: '/webdesign',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnerRequestsRoute = AdminPartnerRequestsRouteImport.update({
  id: '/partner-requests',
  path: '/partner-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFreelancersRoute = AdminFreelancersRouteImport.update({
  id: '/freelancers',
  path: '/freelancers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContractsRoute = AdminContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssignmentsRoute = AdminAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFreelancersIndexRoute = AdminFreelancersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminFreelancersRoute,
} as any)
const AdminContractsIndexRoute = AdminContractsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminContractsRoute,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminClientsRoute,
} as any)
const AdminAssignmentsIndexRoute = AdminAssignmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAssignmentsRoute,
} as any)
const PortalServicesSlugRoute = PortalServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => PortalRoute,
} as any)
const AdminServicesSlugRoute = AdminServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminServicesRoute,
} as any)
const AdminFreelancersSettlementsRoute =
  AdminFreelancersSettlementsRouteImport.update({
    id: '/settlements',
    path: '/settlements',
    getParentRoute: () => AdminFreelancersRoute,
  } as any)
const AdminFreelancersIdRoute = AdminFreelancersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminFreelancersRoute,
} as any)
const AdminContractsNewRoute = AdminContractsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminContractsRoute,
} as any)
const AdminContractsIdRoute = AdminContractsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminContractsRoute,
} as any)
const AdminClientsNewRoute = AdminClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminClientsRoute,
} as any)
const AdminClientsInviteRoute = AdminClientsInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AdminClientsRoute,
} as any)
const AdminClientsClientIdRoute = AdminClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => AdminClientsRoute,
} as any)
const PortalServicesWebdesignMaintenanceRoute =
  PortalServicesWebdesignMaintenanceRouteImport.update({
    id: '/services/webdesign/maintenance',
    path: '/services/webdesign/maintenance',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalServicesSocialMediaScriptsRoute =
  PortalServicesSocialMediaScriptsRouteImport.update({
    id: '/services/social-media/scripts',
    path: '/services/social-media/scripts',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalServicesSocialMediaCalendarRoute =
  PortalServicesSocialMediaCalendarRouteImport.update({
    id: '/services/social-media/calendar',
    path: '/services/social-media/calendar',
    getParentRoute: () => PortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/freelancer': typeof FreelancerRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/admin/assignments': typeof AdminAssignmentsRouteWithChildren
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/contracts': typeof AdminContractsRouteWithChildren
  '/admin/freelancers': typeof AdminFreelancersRouteWithChildren
  '/admin/partner-requests': typeof AdminPartnerRequestsRoute
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/webdesign': typeof AdminWebdesignRoute
  '/freelancer/finance': typeof FreelancerFinanceRoute
  '/freelancer/open': typeof FreelancerOpenRoute
  '/freelancer/requests': typeof FreelancerRequestsRoute
  '/portal/contracts': typeof PortalContractsRoute
  '/sign/$token': typeof SignTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/freelancer/': typeof FreelancerIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/clients/invite': typeof AdminClientsInviteRoute
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/admin/contracts/$id': typeof AdminContractsIdRoute
  '/admin/contracts/new': typeof AdminContractsNewRoute
  '/admin/freelancers/$id': typeof AdminFreelancersIdRoute
  '/admin/freelancers/settlements': typeof AdminFreelancersSettlementsRoute
  '/admin/services/$slug': typeof AdminServicesSlugRoute
  '/portal/services/$slug': typeof PortalServicesSlugRoute
  '/admin/assignments/': typeof AdminAssignmentsIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/contracts/': typeof AdminContractsIndexRoute
  '/admin/freelancers/': typeof AdminFreelancersIndexRoute
  '/portal/services/social-media/calendar': typeof PortalServicesSocialMediaCalendarRoute
  '/portal/services/social-media/scripts': typeof PortalServicesSocialMediaScriptsRoute
  '/portal/services/webdesign/maintenance': typeof PortalServicesWebdesignMaintenanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/partner-requests': typeof AdminPartnerRequestsRoute
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/webdesign': typeof AdminWebdesignRoute
  '/freelancer/finance': typeof FreelancerFinanceRoute
  '/freelancer/open': typeof FreelancerOpenRoute
  '/freelancer/requests': typeof FreelancerRequestsRoute
  '/portal/contracts': typeof PortalContractsRoute
  '/sign/$token': typeof SignTokenRoute
  '/admin': typeof AdminIndexRoute
  '/freelancer': typeof FreelancerIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/clients/invite': typeof AdminClientsInviteRoute
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/admin/contracts/$id': typeof AdminContractsIdRoute
  '/admin/contracts/new': typeof AdminContractsNewRoute
  '/admin/freelancers/$id': typeof AdminFreelancersIdRoute
  '/admin/freelancers/settlements': typeof AdminFreelancersSettlementsRoute
  '/admin/services/$slug': typeof AdminServicesSlugRoute
  '/portal/services/$slug': typeof PortalServicesSlugRoute
  '/admin/assignments': typeof AdminAssignmentsIndexRoute
  '/admin/clients': typeof AdminClientsIndexRoute
  '/admin/contracts': typeof AdminContractsIndexRoute
  '/admin/freelancers': typeof AdminFreelancersIndexRoute
  '/portal/services/social-media/calendar': typeof PortalServicesSocialMediaCalendarRoute
  '/portal/services/social-media/scripts': typeof PortalServicesSocialMediaScriptsRoute
  '/portal/services/webdesign/maintenance': typeof PortalServicesWebdesignMaintenanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/freelancer': typeof FreelancerRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/admin/assignments': typeof AdminAssignmentsRouteWithChildren
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/contracts': typeof AdminContractsRouteWithChildren
  '/admin/freelancers': typeof AdminFreelancersRouteWithChildren
  '/admin/partner-requests': typeof AdminPartnerRequestsRoute
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/webdesign': typeof AdminWebdesignRoute
  '/freelancer/finance': typeof FreelancerFinanceRoute
  '/freelancer/open': typeof FreelancerOpenRoute
  '/freelancer/requests': typeof FreelancerRequestsRoute
  '/portal/contracts': typeof PortalContractsRoute
  '/sign/$token': typeof SignTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/freelancer/': typeof FreelancerIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/clients/invite': typeof AdminClientsInviteRoute
  '/admin/clients/new': typeof AdminClientsNewRoute
  '/admin/contracts/$id': typeof AdminContractsIdRoute
  '/admin/contracts/new': typeof AdminContractsNewRoute
  '/admin/freelancers/$id': typeof AdminFreelancersIdRoute
  '/admin/freelancers/settlements': typeof AdminFreelancersSettlementsRoute
  '/admin/services/$slug': typeof AdminServicesSlugRoute
  '/portal/services/$slug': typeof PortalServicesSlugRoute
  '/admin/assignments/': typeof AdminAssignmentsIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/contracts/': typeof AdminContractsIndexRoute
  '/admin/freelancers/': typeof AdminFreelancersIndexRoute
  '/portal/services/social-media/calendar': typeof PortalServicesSocialMediaCalendarRoute
  '/portal/services/social-media/scripts': typeof PortalServicesSocialMediaScriptsRoute
  '/portal/services/webdesign/maintenance': typeof PortalServicesWebdesignMaintenanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/freelancer'
    | '/login'
    | '/portal'
    | '/admin/assignments'
    | '/admin/clients'
    | '/admin/contracts'
    | '/admin/freelancers'
    | '/admin/partner-requests'
    | '/admin/services'
    | '/admin/webdesign'
    | '/freelancer/finance'
    | '/freelancer/open'
    | '/freelancer/requests'
    | '/portal/contracts'
    | '/sign/$token'
    | '/admin/'
    | '/freelancer/'
    | '/portal/'
    | '/admin/clients/$clientId'
    | '/admin/clients/invite'
    | '/admin/clients/new'
    | '/admin/contracts/$id'
    | '/admin/contracts/new'
    | '/admin/freelancers/$id'
    | '/admin/freelancers/settlements'
    | '/admin/services/$slug'
    | '/portal/services/$slug'
    | '/admin/assignments/'
    | '/admin/clients/'
    | '/admin/contracts/'
    | '/admin/freelancers/'
    | '/portal/services/social-media/calendar'
    | '/portal/services/social-media/scripts'
    | '/portal/services/webdesign/maintenance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/admin/partner-requests'
    | '/admin/services'
    | '/admin/webdesign'
    | '/freelancer/finance'
    | '/freelancer/open'
    | '/freelancer/requests'
    | '/portal/contracts'
    | '/sign/$token'
    | '/admin'
    | '/freelancer'
    | '/portal'
    | '/admin/clients/$clientId'
    | '/admin/clients/invite'
    | '/admin/clients/new'
    | '/admin/contracts/$id'
    | '/admin/contracts/new'
    | '/admin/freelancers/$id'
    | '/admin/freelancers/settlements'
    | '/admin/services/$slug'
    | '/portal/services/$slug'
    | '/admin/assignments'
    | '/admin/clients'
    | '/admin/contracts'
    | '/admin/freelancers'
    | '/portal/services/social-media/calendar'
    | '/portal/services/social-media/scripts'
    | '/portal/services/webdesign/maintenance'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/freelancer'
    | '/login'
    | '/portal'
    | '/admin/assignments'
    | '/admin/clients'
    | '/admin/contracts'
    | '/admin/freelancers'
    | '/admin/partner-requests'
    | '/admin/services'
    | '/admin/webdesign'
    | '/freelancer/finance'
    | '/freelancer/open'
    | '/freelancer/requests'
    | '/portal/contracts'
    | '/sign/$token'
    | '/admin/'
    | '/freelancer/'
    | '/portal/'
    | '/admin/clients/$clientId'
    | '/admin/clients/invite'
    | '/admin/clients/new'
    | '/admin/contracts/$id'
    | '/admin/contracts/new'
    | '/admin/freelancers/$id'
    | '/admin/freelancers/settlements'
    | '/admin/services/$slug'
    | '/portal/services/$slug'
    | '/admin/assignments/'
    | '/admin/clients/'
    | '/admin/contracts/'
    | '/admin/freelancers/'
    | '/portal/services/social-media/calendar'
    | '/portal/services/social-media/scripts'
    | '/portal/services/webdesign/maintenance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FreelancerRoute: typeof FreelancerRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  SignTokenRoute: typeof SignTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer': {
      id: '/freelancer'
      path: '/freelancer'
      fullPath: '/freelancer'
      preLoaderRoute: typeof FreelancerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/freelancer/': {
      id: '/freelancer/'
      path: '/'
      fullPath: '/freelancer/'
      preLoaderRoute: typeof FreelancerIndexRouteImport
      parentRoute: typeof FreelancerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/contracts': {
      id: '/portal/contracts'
      path: '/contracts'
      fullPath: '/portal/contracts'
      preLoaderRoute: typeof PortalContractsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/freelancer/requests': {
      id: '/freelancer/requests'
      path: '/requests'
      fullPath: '/freelancer/requests'
      preLoaderRoute: typeof FreelancerRequestsRouteImport
      parentRoute: typeof FreelancerRoute
    }
    '/freelancer/open': {
      id: '/freelancer/open'
      path: '/open'
      fullPath: '/freelancer/open'
      preLoaderRoute: typeof FreelancerOpenRouteImport
      parentRoute: typeof FreelancerRoute
    }
    '/freelancer/finance': {
      id: '/freelancer/finance'
      path: '/finance'
      fullPath: '/freelancer/finance'
      preLoaderRoute: typeof FreelancerFinanceRouteImport
      parentRoute: typeof FreelancerRoute
    }
    '/admin/webdesign': {
      id: '/admin/webdesign'
      path: '/webdesign'
      fullPath: '/admin/webdesign'
      preLoaderRoute: typeof AdminWebdesignRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partner-requests': {
      id: '/admin/partner-requests'
      path: '/partner-requests'
      fullPath: '/admin/partner-requests'
      preLoaderRoute: typeof AdminPartnerRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/freelancers': {
      id: '/admin/freelancers'
      path: '/freelancers'
      fullPath: '/admin/freelancers'
      preLoaderRoute: typeof AdminFreelancersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contracts': {
      id: '/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AdminContractsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assignments': {
      id: '/admin/assignments'
      path: '/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AdminAssignmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/freelancers/': {
      id: '/admin/freelancers/'
      path: '/'
      fullPath: '/admin/freelancers/'
      preLoaderRoute: typeof AdminFreelancersIndexRouteImport
      parentRoute: typeof AdminFreelancersRoute
    }
    '/admin/contracts/': {
      id: '/admin/contracts/'
      path: '/'
      fullPath: '/admin/contracts/'
      preLoaderRoute: typeof AdminContractsIndexRouteImport
      parentRoute: typeof AdminContractsRoute
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof AdminClientsRoute
    }
    '/admin/assignments/': {
      id: '/admin/assignments/'
      path: '/'
      fullPath: '/admin/assignments/'
      preLoaderRoute: typeof AdminAssignmentsIndexRouteImport
      parentRoute: typeof AdminAssignmentsRoute
    }
    '/portal/services/$slug': {
      id: '/portal/services/$slug'
      path: '/services/$slug'
      fullPath: '/portal/services/$slug'
      preLoaderRoute: typeof PortalServicesSlugRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/services/$slug': {
      id: '/admin/services/$slug'
      path: '/$slug'
      fullPath: '/admin/services/$slug'
      preLoaderRoute: typeof AdminServicesSlugRouteImport
      parentRoute: typeof AdminServicesRoute
    }
    '/admin/freelancers/settlements': {
      id: '/admin/freelancers/settlements'
      path: '/settlements'
      fullPath: '/admin/freelancers/settlements'
      preLoaderRoute: typeof AdminFreelancersSettlementsRouteImport
      parentRoute: typeof AdminFreelancersRoute
    }
    '/admin/freelancers/$id': {
      id: '/admin/freelancers/$id'
      path: '/$id'
      fullPath: '/admin/freelancers/$id'
      preLoaderRoute: typeof AdminFreelancersIdRouteImport
      parentRoute: typeof AdminFreelancersRoute
    }
    '/admin/contracts/new': {
      id: '/admin/contracts/new'
      path: '/new'
      fullPath: '/admin/contracts/new'
      preLoaderRoute: typeof AdminContractsNewRouteImport
      parentRoute: typeof AdminContractsRoute
    }
    '/admin/contracts/$id': {
      id: '/admin/contracts/$id'
      path: '/$id'
      fullPath: '/admin/contracts/$id'
      preLoaderRoute: typeof AdminContractsIdRouteImport
      parentRoute: typeof AdminContractsRoute
    }
    '/admin/clients/new': {
      id: '/admin/clients/new'
      path: '/new'
      fullPath: '/admin/clients/new'
      preLoaderRoute: typeof AdminClientsNewRouteImport
      parentRoute: typeof AdminClientsRoute
    }
    '/admin/clients/invite': {
      id: '/admin/clients/invite'
      path: '/invite'
      fullPath: '/admin/clients/invite'
      preLoaderRoute: typeof AdminClientsInviteRouteImport
      parentRoute: typeof AdminClientsRoute
    }
    '/admin/clients/$clientId': {
      id: '/admin/clients/$clientId'
      path: '/$clientId'
      fullPath: '/admin/clients/$clientId'
      preLoaderRoute: typeof AdminClientsClientIdRouteImport
      parentRoute: typeof AdminClientsRoute
    }
    '/portal/services/webdesign/maintenance': {
      id: '/portal/services/webdesign/maintenance'
      path: '/services/webdesign/maintenance'
      fullPath: '/portal/services/webdesign/maintenance'
      preLoaderRoute: typeof PortalServicesWebdesignMaintenanceRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/services/social-media/scripts': {
      id: '/portal/services/social-media/scripts'
      path: '/services/social-media/scripts'
      fullPath: '/portal/services/social-media/scripts'
      preLoaderRoute: typeof PortalServicesSocialMediaScriptsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/services/social-media/calendar': {
      id: '/portal/services/social-media/calendar'
      path: '/services/social-media/calendar'
      fullPath: '/portal/services/social-media/calendar'
      preLoaderRoute: typeof PortalServicesSocialMediaCalendarRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface AdminAssignmentsRouteChildren {
  AdminAssignmentsIndexRoute: typeof AdminAssignmentsIndexRoute
}

const AdminAssignmentsRouteChildren: AdminAssignmentsRouteChildren = {
  AdminAssignmentsIndexRoute: AdminAssignmentsIndexRoute,
}

const AdminAssignmentsRouteWithChildren =
  AdminAssignmentsRoute._addFileChildren(AdminAssignmentsRouteChildren)

interface AdminClientsRouteChildren {
  AdminClientsClientIdRoute: typeof AdminClientsClientIdRoute
  AdminClientsInviteRoute: typeof AdminClientsInviteRoute
  AdminClientsNewRoute: typeof AdminClientsNewRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
}

const AdminClientsRouteChildren: AdminClientsRouteChildren = {
  AdminClientsClientIdRoute: AdminClientsClientIdRoute,
  AdminClientsInviteRoute: AdminClientsInviteRoute,
  AdminClientsNewRoute: AdminClientsNewRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
}

const AdminClientsRouteWithChildren = AdminClientsRoute._addFileChildren(
  AdminClientsRouteChildren,
)

interface AdminContractsRouteChildren {
  AdminContractsIdRoute: typeof AdminContractsIdRoute
  AdminContractsNewRoute: typeof AdminContractsNewRoute
  AdminContractsIndexRoute: typeof AdminContractsIndexRoute
}

const AdminContractsRouteChildren: AdminContractsRouteChildren = {
  AdminContractsIdRoute: AdminContractsIdRoute,
  AdminContractsNewRoute: AdminContractsNewRoute,
  AdminContractsIndexRoute: AdminContractsIndexRoute,
}

const AdminContractsRouteWithChildren = AdminContractsRoute._addFileChildren(
  AdminContractsRouteChildren,
)

interface AdminFreelancersRouteChildren {
  AdminFreelancersIdRoute: typeof AdminFreelancersIdRoute
  AdminFreelancersSettlementsRoute: typeof AdminFreelancersSettlementsRoute
  AdminFreelancersIndexRoute: typeof AdminFreelancersIndexRoute
}

const AdminFreelancersRouteChildren: AdminFreelancersRouteChildren = {
  AdminFreelancersIdRoute: AdminFreelancersIdRoute,
  AdminFreelancersSettlementsRoute: AdminFreelancersSettlementsRoute,
  AdminFreelancersIndexRoute: AdminFreelancersIndexRoute,
}

const AdminFreelancersRouteWithChildren =
  AdminFreelancersRoute._addFileChildren(AdminFreelancersRouteChildren)

interface AdminServicesRouteChildren {
  AdminServicesSlugRoute: typeof AdminServicesSlugRoute
}

const AdminServicesRouteChildren: AdminServicesRouteChildren = {
  AdminServicesSlugRoute: AdminServicesSlugRoute,
}

const AdminServicesRouteWithChildren = AdminServicesRoute._addFileChildren(
  AdminServicesRouteChildren,
)

interface AdminRouteChildren {
  AdminAssignmentsRoute: typeof AdminAssignmentsRouteWithChildren
  AdminClientsRoute: typeof AdminClientsRouteWithChildren
  AdminContractsRoute: typeof AdminContractsRouteWithChildren
  AdminFreelancersRoute: typeof AdminFreelancersRouteWithChildren
  AdminPartnerRequestsRoute: typeof AdminPartnerRequestsRoute
  AdminServicesRoute: typeof AdminServicesRouteWithChildren
  AdminWebdesignRoute: typeof AdminWebdesignRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssignmentsRoute: AdminAssignmentsRouteWithChildren,
  AdminClientsRoute: AdminClientsRouteWithChildren,
  AdminContractsRoute: AdminContractsRouteWithChildren,
  AdminFreelancersRoute: AdminFreelancersRouteWithChildren,
  AdminPartnerRequestsRoute: AdminPartnerRequestsRoute,
  AdminServicesRoute: AdminServicesRouteWithChildren,
  AdminWebdesignRoute: AdminWebdesignRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FreelancerRouteChildren {
  FreelancerFinanceRoute: typeof FreelancerFinanceRoute
  FreelancerOpenRoute: typeof FreelancerOpenRoute
  FreelancerRequestsRoute: typeof FreelancerRequestsRoute
  FreelancerIndexRoute: typeof FreelancerIndexRoute
}

const FreelancerRouteChildren: FreelancerRouteChildren = {
  FreelancerFinanceRoute: FreelancerFinanceRoute,
  FreelancerOpenRoute: FreelancerOpenRoute,
  FreelancerRequestsRoute: FreelancerRequestsRoute,
  FreelancerIndexRoute: FreelancerIndexRoute,
}

const FreelancerRouteWithChildren = FreelancerRoute._addFileChildren(
  FreelancerRouteChildren,
)

interface PortalRouteChildren {
  PortalContractsRoute: typeof PortalContractsRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalServicesSlugRoute: typeof PortalServicesSlugRoute
  PortalServicesSocialMediaCalendarRoute: typeof PortalServicesSocialMediaCalendarRoute
  PortalServicesSocialMediaScriptsRoute: typeof PortalServicesSocialMediaScriptsRoute
  PortalServicesWebdesignMaintenanceRoute: typeof PortalServicesWebdesignMaintenanceRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalContractsRoute: PortalContractsRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalServicesSlugRoute: PortalServicesSlugRoute,
  PortalServicesSocialMediaCalendarRoute:
    PortalServicesSocialMediaCalendarRoute,
  PortalServicesSocialMediaScriptsRoute: PortalServicesSocialMediaScriptsRoute,
  PortalServicesWebdesignMaintenanceRoute:
    PortalServicesWebdesignMaintenanceRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FreelancerRoute: FreelancerRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  SignTokenRoute: SignTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
